export const projects = [
	{
		img: 'https://miro.medium.com/max/1400/1*QagJietk4g2cDfoq9rAxlQ.jpeg',
		title: 'Clone of ZARA',
		des: 'Zara is one of the largest international fashion companies. It belongs to Inditex, one of the world’s largest distribution groups..',
		demo: '',
		live: 'https://zara-replica.netlify.app/',
		gitHub: 'https://github.com/divyansh050/ZARA-CLONE',
		technologies: ['React', 'MongoDb', 'Nodejs',"Express" ,'CSS'],
	},
	{
		img: 'https://user-images.githubusercontent.com/66282953/158450698-03e2595e-6e6d-4649-9216-6c3175647bab.png',
		title: 'Clone of Lakme',
		des: 'Lakme is a beauty product website which deals in each and every type of beauty product & its collection.This website has features such as users can buy product,select the product,checkout.',
		demo: '',
		live: 'https://sauravsaran99.github.io/lakmeindia/',
		gitHub: 'https://github.com/sauravsaran99/lakmeindia',
		technologies: [ 'HTML', 'CSS',"JavaScript","Bootstrap"],
	},
	// {
	// 	img: 'https://user-images.githubusercontent.com/86410034/129320136-4642eb9e-8500-4058-a8c3-440bb38dafc7.png',
	// 	title: 'Clone of Bluemercury',
	// 	des: 'This is a clone of a US-based e-commerce website for cosmetic products built with HTML, CSS, and JS Has features that allow user live search of the products with a sorting feature.',
	// 	demo: '',
	// 	live: 'https://bluemercuryclone.netlify.app/html/homepage.html',
	// 	gitHub: 'https://github.com/Nitesh-Goshwami/Bluemercury',
	// 	technologies: ['HTML', 'CSS', 'javaScript'],
	// },
	// {
		// 	img: 'https://camo.githubusercontent.com/b7f4aa8c34ddf776dd19b78dc3488456470a73e5026f48784e9e753601468802/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4c62507030307771454537386c6f68584d372f67697068792e676966',
		// 	title: 'Clone of Fitness Blender',
		// 	des: 'This is a clone of the Fitness Blender website. The clone is complete with a Login page, Sign-in page, Shopping Cart, Wishlist and Calendar Scheduling feature. Following is the link to the clone of the website.',
		// 	demo: '',
		// 	live: 'https://anshusagar.github.io/FitnessBlender/',
		// 	gitHub: 'https://github.com/Anshusagar/FitnessBlender.git',
		// 	technologies: ['HTML', 'CSS', 'javaScript'],
		// },
		// {
			// 	img: 'https://github.com/mandarsatam/Mailchimp-Clone/blob/master/Snips/Screenshot%20(79).png?raw=true',
			// 	title: 'Mailchimp Clone',
			// 	des: 'This is a static clone of a website called Mailchimp. This clone includes landing, pricing, our story, and the resources page.',
			// 	demo: '',
			// 	live: 'https://mandarsatam.github.io/Mailchimp-Clone/',
	// 	gitHub: 'https://github.com/mandarsatam/Mailchimp-Clone',
	// 	technologies: ['HTML', 'CSS', 'javaScript'],
	// },
	// {
	// 	img: 'https://user-images.githubusercontent.com/86410106/143928012-c66d0c3c-1f94-4894-b1f0-2326be4f3087.png',
	// 	title: 'Clone of Target.com ',
	// 	des: 'This is a clone of a US-based e-commerce website for all products built with HTML, CSS, JS. Have features that allow users to sort the product on the basis of price, on the payment page users can apply promo codes',
	// 	demo: '',
	// 	live: 'https://pandeypushpendra3.github.io/target/', // deployed link
	// 	gitHub: 'https://github.com/pandeypushpendra3/target/tree/main',
	// 	technologies: [ 'HTML', 'CSS', 'javaScript'],
	// },
];
