export const projects = [
	{
		img: process.env.PUBLIC_URL + '/echo-ai.png',
		title: 'Echo AI – AI Powered Conversational Platform',
		des: 'An AI-powered conversational platform built on the MERN stack with intelligent chat workflows, scalable backend services, authentication systems, and AI-driven automation. Integrated OpenAI-based conversation workflows, REST APIs, user management, and optimized performance and scalability.',
		demo: '',
		live: 'https://echo-ai.nxtgenaidev.com/',
		gitHub: '',
		technologies: ['React', 'Node js', 'Express', 'MongoDB', 'REST APIs', 'AI Integration'],
	},
	{
		img: process.env.PUBLIC_URL + '/elevence-ai.svg',
		title: 'Elevence AI – AI Powered Platform',
		des: 'An AI-powered full-stack platform built with MERN architecture focusing on scalable backend services, responsive frontend development, AI workflow integration, and performance optimization. Designed MongoDB schemas, built REST APIs, and implemented authentication and data management.',
		demo: '',
		live: 'https://www.nxtgenaidev.com/products/elevence-ai',
		gitHub: '',
		technologies: ['React', 'Node js', 'Express', 'MongoDB', 'REST APIs', 'AI Integration'],
	},
	{
		img: process.env.PUBLIC_URL + '/palletRack.png',
		title: 'Pallet Rack Market – Logistics & Pallet Tracking',
		des: 'A full-stack logistics and pallet tracking platform to manage inventory movement, shipment tracking, and operational processes. Built real-time tracking workflows, dashboards, role-based access control, and optimized database schemas for high-volume operations.',
		demo: '',
		live: 'https://palletrackdev-a27ce23e7fa2.herokuapp.com/',
		gitHub: '',
		technologies: ['React', 'Node js', 'Express', 'MongoDB', 'PostgreSQL', 'AWS', 'Heroku'],
	},
	{
		img: process.env.PUBLIC_URL + '/gfhr.png',
		title: 'Global Family Home Rentals',
		des: 'A full-stack accommodation and travel platform for long-term family travel, with property listings, booking workflows, membership management, and dashboards. Built scalable backend APIs, authentication, role-based access, and optimized performance and cloud deployment.',
		demo: '',
		live: 'https://gfhr-dev-c7212ab00a8a.herokuapp.com/',
		gitHub: '',
		technologies: ['React', 'Node js', 'Express', 'MongoDB', 'PostgreSQL', 'AWS', 'Heroku'],
	},
	{
		img: 'https://miro.medium.com/max/1400/1*QagJietk4g2cDfoq9rAxlQ.jpeg',
		title: 'Clone of ZARA',
		des: 'Zara is one of the largest international fashion companies. It belongs to Inditex, one of the world\'s largest distribution groups.',
		demo: '',
		live: 'https://zara-replica.netlify.app/',
		gitHub: 'https://github.com/divyansh050/ZARA-CLONE',
		technologies: ['React', 'MongoDB', 'Node js', 'Express', 'CSS'],
	},
	{
		img: 'https://user-images.githubusercontent.com/66282953/158450698-03e2595e-6e6d-4649-9216-6c3175647bab.png',
		title: 'Clone of Lakme',
		des: 'Lakme is a beauty product website which deals in each and every type of beauty product. Features include buying products, selecting items and checkout.',
		demo: '',
		live: 'https://sauravsaran99.github.io/lakmeindia/',
		gitHub: 'https://github.com/sauravsaran99/lakmeindia',
		technologies: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
	},
	{
		img: 'https://github.com/bablikumari2/APARTMENT-MANAGER/raw/main/fornted/manager/public/image/Screenshot%20(337).png?raw=true',
		title: 'Apartment Manager',
		des: 'A React app to manage resident details in a society with full CRUD operations.',
		demo: '',
		live: 'https://manager-self-psi.vercel.app/',
		gitHub: 'https://github.com/bablikumari2/APARTMENT-MANAGER',
		technologies: ['React', 'Redux', 'JavaScript', 'Express', 'Node js', 'Mongoose'],
	},
	{
		img: 'https://github.com/bablikumari2/chat-clone/blob/main/client/public/Image/chatting%20room.png?raw=true',
		title: 'Chit Chat – Real-time Chat App',
		des: 'A real-time chat application with live messaging powered by Socket.io.',
		demo: '',
		live: 'https://client-omega-murex.vercel.app/',
		gitHub: 'https://github.com/bablikumari2/chat-clone',
		technologies: ['React', 'Redux', 'JavaScript', 'Express', 'Node js', 'Socket.io'],
	},
];
